### ISSUE TITLE
Automatische Trennung des Wortes Anfängerkrebs

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/anfaengerkrebs.de#1]
In der mobile Ansicht wird das Wort "Anfängerkrebs" nicht automatisch umgebrochen. Das sieht natürlich total blöd aus.

<img width="323" alt="Bildschirmfoto 2020-01-13 um 16 33 15" src="https://user-images.githubusercontent.com/69770/72268655-7e103200-3622-11ea-989b-1811773558a5.png">

**Comment by xamiam** [comment]
Geht. Entweder per https://getbootstrap.com/docs/4.4/utilities/display/ (hier werden abhängig von den Breakpoints Inhalte ein- und ausgeblendet) oder über CSS (dann hat man allerdings keine gute Kontrolle, wann getrennt wird):

CSS
`  overflow-wrap: break-word;  
  word-wrap: break-word;  
  hyphens: auto;
`

**Comment by wintermeyer** [comment]
Fixed by @xamiam 

Desktop:
<img width="1430" alt="Bildschirmfoto 2020-01-14 um 21 16 16" src="https://user-images.githubusercontent.com/69770/72379378-98760880-3713-11ea-9921-e4b61b27d8fc.png">

Mobile:
<img width="325" alt="Bildschirmfoto 2020-01-14 um 21 20 07" src="https://user-images.githubusercontent.com/69770/72379418-aaf04200-3713-11ea-9268-13053c96561d.png">
