### ISSUE TITLE
Abgeschnittene Ä-Punkte

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/anfaengerkrebs.de#2]
Beim Wort "ANFÄNGERKREBS" ist ein Teil der Ä-Punkte abgeschnitten (Safari macOS). Kann man das fixen oder muss man eine andere Schrift benutzen?

<img width="446" alt="Bildschirmfoto 2020-01-13 um 16 35 00" src="https://user-images.githubusercontent.com/69770/72268751-b0ba2a80-3622-11ea-8f01-501160f16da2.png">

**Comment by xamiam** [comment]
Kann man fixen. Kommt durch eine Maske für die Schrift zustande und overflow:hidden.
