### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/anfaengerkrebs.de#3]
Intro: WebPerformance spielt jetzt erst mal keine Rolle bei dieser Seite.

Die Seite sieht aktuell ungefähr so aus (work in progress):
<img width="1430" alt="Bildschirmfoto 2020-01-13 um 16 48 07" src="https://user-images.githubusercontent.com/69770/72269846-8bc6b700-3624-11ea-900e-e2a414b1b73b.png">

Beim Podcast Cover spiele ich gerade mit folgender Idee (work in progress, da stimmt noch ne Menge nicht):

![podcast](https://user-images.githubusercontent.com/69770/72269560-12c75f80-3624-11ea-9a17-8c08a66c0a1b.png)

Ich muss mich jetzt auf eine Schriftart festlegen. Dann kann ich die Webseite und das Cover fertig machen.

**Comment by xamiam** [comment]
Ich werfe mal https://fonts.google.com/specimen/Muli in den Raum...
Funktioniert für alles. Wenn Performance keine Rolle spielt, dann einfach über Google Fonts einbinden, ansonsten per https://google-webfonts-helper.herokuapp.com/fonts selbst hosten.

**Comment by wintermeyer** [comment]
Done by @xamiam 

<img width="1430" alt="Bildschirmfoto 2020-01-14 um 21 16 16" src="https://user-images.githubusercontent.com/69770/72379158-30272700-3713-11ea-916b-53f48d1606e7.png">
