### ISSUE TITLE
iPhone X above the fold ohne den Audio-Teil im Fuss

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/anfaengerkrebs.de#5]
Wenn man https://www.anfaengerkrebs.de aufruft, dann sieht das auf dem iPhone X so aus:

![IMG_0646](https://user-images.githubusercontent.com/69770/72665993-04a38580-3a0e-11ea-8d48-1088028c10d7.jpeg)

Für den Audio-Teil muss man scrollen. Das ist natürlich suboptimal.

@xamiam Kannst Du das so machen, das man den Teil, der auf dem Desktop unten sichtbar ist, auch auf allen mobilen Geräten unten sichtbar hat?

**Comment by xamiam** [comment]
fixed.

**Comment by wintermeyer** [comment]
e09720c56a2148957701e35acf3a89cf2d7f320b

**Comment by wintermeyer** [comment]
Das reicht noch nicht. Das ist zu knapp.  Darunter kommt ja noch der subscribe Button. 

![79C486D1-B7EC-4099-AC6D-F7F65CAA4E0B](https://user-images.githubusercontent.com/69770/72708659-822cda00-3b63-11ea-8a98-4120dfb0ed24.png)

**Comment by xamiam** [comment]
Hey Stefan,

ich habe die Höhe nun erneut angepasst. Problem ist die Navigation vom Browser, die die eigentliche Höhe überlagert (weil der Hintergrund durchscheint). Der subscribe-Button schiebt das dann noch weiter nach oben...

**Comment by wintermeyer** [comment]
Hast Du eine Idee, warum es jetzt so aussieht?

![F35A774C-DD92-4084-8AD9-953B93DFCB04](https://user-images.githubusercontent.com/69770/72846286-962a2600-3ca0-11ea-9d11-13605959f0c8.png)

**Comment by wintermeyer** [comment]
Geht jetzt. Wohl ein Caching Problem.
